# Generated by Django 4.2.6 on 2023-10-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviedata",
            name="type",
            field=models.CharField(default="action", max_length=200),
        ),
    ]
